routes/web.php
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});
Route::get('',                    ['as' => 'index',             'uses' => 'WebPage\WebPageController@index']);
Route::get('about',                    ['as' => 'about',             'uses' => 'WebPage\WebPageController@about']);
Route::get('gallerys',                    ['as' => 'gallery',             'uses' => 'WebPage\WebPageController@gallery']);
Route::get('gallerys/{slug}',                    ['as' => 'photo',             'uses' => 'WebPage\WebPageController@gallery']);
Route::get('contact-us',                    ['as' => 'contact-us',             'uses' => 'WebPage\WebPageController@contact']);
Route::get('newses/{slug}',                    ['as' => 'newss',             'uses' => 'WebPage\WebPageController@news']);
Route::get('newses',                    ['as' => 'newses',             'uses' => 'WebPage\WebPageController@news']);
Route::get('alumni',                    ['as' => 'alumni',             'uses' => 'WebPage\WebPageController@alumni']);
Route::get('careers',                    ['as' => 'careers',             'uses' => 'WebPage\WebPageController@careers']);
Route::get('informations',                    ['as' => 'informations',             'uses' => 'WebPage\WebPageController@information']);
Route::get('club-and-ecas',                    ['as' => 'club-and-eca',             'uses' => 'WebPage\WebPageController@clubAndEca']);
Route::get('downloads',                    ['as' => 'download',             'uses' => 'WebPage\WebPageController@download']);
Route::get('simplepage/{slug}',                    ['as' => 'simplepage',             'uses' => 'WebPage\WebPageController@page']);
Route::post('feedback/stores',                 ['as' => 'feedback.store',           'uses' => 'Admin\FeedbackController@store']);

Auth::routes();

//Route::get('/', function () {
//    return redirect('login');
//});

Route::get('/home', function () {
    return redirect()->route('admin.dashboard');
});

Route::group(['middleware' => ['auth', 'status'], 'prefix' => '', 'as' => 'admin.', 'namespace' => 'Admin\\'], function () {

    Route::get('dashboard', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
    Route::get('error/{code}',                        ['as' => 'error',                 'uses' => 'DashboardController@error']);

    Route::get('profile', ['as' => 'profile', 'uses' => 'ProfileController@edit']);
    Route::post('profile/{id}/update', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::post('profile/{id}/delete', ['as' => 'profile.delete', 'uses' => 'ProfileController@delete']);

    Route::get('menu',['as' => 'menu', 'uses' => 'MenuController@index']);

    Route::get('principle',                    ['as' => 'principle.add',             'uses' => 'PrincipleController@add']);
    Route::post('principle/{id}/update',          ['as' => 'principle.update',          'uses' => 'PrincipleController@update']);
    Route::post('principle/{id}/delete',          ['as' => 'principle.image.delete',          'uses' => 'PrincipleController@imageDelete']);

    Route::get('about-us',                        ['as' => 'about-us.index',           'uses' => 'AboutUsController@index']);
    Route::post('about-us-search',                        ['as' => 'about-us.search',           'uses' => 'AboutUsController@search']);
    Route::get('about-us/add',                    ['as' => 'about-us.add',             'uses' => 'AboutUsController@add']);
    Route::post('about-us/store',                 ['as' => 'about-us.store',           'uses' => 'AboutUsController@store']);
    Route::get('about-us/{menu_id}/{page_id}/edit',              ['as' => 'about-us.edit',            'uses' => 'AboutUsController@edit']);
    Route::post('about-us/{menu_id}/{page_id}/update',          ['as' => 'about-us.update',          'uses' => 'AboutUsController@update']);
    Route::get('about-us/{menu_id}/{page_id}/delete',           ['as' => 'about-us.delete',          'uses' => 'AboutUsController@delete']);
    Route::post('about-us/delete',           ['as' => 'image.about-us.delete',          'uses' => 'AboutUsController@imgDelete']);

    Route::get('information',                        ['as' => 'information.index',           'uses' => 'InformationController@index']);
    Route::post('information-search',                        ['as' => 'information.search',           'uses' => 'InformationController@search']);
    Route::get('information/add',                    ['as' => 'information.add',             'uses' => 'InformationController@add']);
    Route::post('information/store',                 ['as' => 'information.store',           'uses' => 'InformationController@store']);
    Route::get('information/{menu_id}/{page_id}/edit',              ['as' => 'information.edit',            'uses' => 'InformationController@edit']);
    Route::post('information/{menu_id}/{page_id}/update',          ['as' => 'information.update',          'uses' => 'InformationController@update']);
    Route::get('information/{menu_id}/{page_id}/delete',           ['as' => 'information.delete',          'uses' => 'InformationController@delete']);
    Route::post('information/delete',           ['as' => 'image.information.delete',          'uses' => 'InformationController@imgDelete']);

    Route::get('club-and-eca',                        ['as' => 'club-and-eca.index',           'uses' => 'ClubAndEcaController@index']);
    Route::post('club-and-eca-search',                        ['as' => 'club-and-eca.search',           'uses' => 'ClubAndEcaController@search']);
    Route::get('club-and-eca/add',                    ['as' => 'club-and-eca.add',             'uses' => 'ClubAndEcaController@add']);
    Route::post('club-and-eca/store',                 ['as' => 'club-and-eca.store',           'uses' => 'ClubAndEcaController@store']);
    Route::get('club-and-eca/{menu_id}/{page_id}/edit',              ['as' => 'club-and-eca.edit',            'uses' => 'ClubAndEcaController@edit']);
    Route::post('club-and-eca/{menu_id}/{page_id}/update',          ['as' => 'club-and-eca.update',          'uses' => 'ClubAndEcaController@update']);
    Route::get('club-and-eca/{menu_id}/{page_id}/delete',           ['as' => 'club-and-eca.delete',          'uses' => 'ClubAndEcaController@delete']);
    Route::post('club-and-eca/delete',           ['as' => 'image.club-and-eca.delete',          'uses' => 'ClubAndEcaController@imgDelete']);

    Route::get('gallery',                        ['as' => 'gallery.index',           'uses' => 'GalleryController@index']);
    Route::get('gallery/add',                    ['as' => 'gallery.add',             'uses' => 'GalleryController@add']);
    Route::post('gallery/store',                 ['as' => 'gallery.store',           'uses' => 'GalleryController@store']);
    Route::get('gallery/{id}/edit',              ['as' => 'gallery.edit',            'uses' => 'GalleryController@edit']);
    Route::post('gallery/{id}/update',          ['as' => 'gallery.update',          'uses' => 'GalleryController@update']);
    Route::get('gallery/{id}/delete',           ['as' => 'gallery.delete',          'uses' => 'GalleryController@delete']);

    Route::get('photo',                        ['as' => 'photo.index',           'uses' => 'PhotoController@index']);
    Route::get('photo/add',                    ['as' => 'photo.add',             'uses' => 'PhotoController@add']);
    Route::post('photo/store',                 ['as' => 'photo.store',           'uses' => 'PhotoController@store']);
    Route::get('photo/{id}/edit',              ['as' => 'photo.edit',            'uses' => 'PhotoController@edit']);
    Route::post('photo/{id}/update',          ['as' => 'photo.update',          'uses' => 'PhotoController@update']);
    Route::get('photo/{id}/delete',           ['as' => 'photo.delete',          'uses' => 'PhotoController@delete']);

    Route::get('feature',                        ['as' => 'feature.index',           'uses' => 'FeatureController@index']);
    Route::get('feature/add',                    ['as' => 'feature.add',             'uses' => 'FeatureController@add']);
    Route::post('feature/store',                 ['as' => 'feature.store',           'uses' => 'FeatureController@store']);
    Route::get('feature/{id}/edit',              ['as' => 'feature.edit',            'uses' => 'FeatureController@edit']);
    Route::post('feature/{id}/update',          ['as' => 'feature.update',          'uses' => 'FeatureController@update']);
    Route::get('feature/{id}/delete',           ['as' => 'feature.delete',          'uses' => 'FeatureController@delete']);

    Route::get('feedback',                        ['as' => 'feedback.index',           'uses' => 'FeedbackController@index']);
    Route::get('feedback/add',                    ['as' => 'feedback.add',             'uses' => 'FeedbackController@add']);
    Route::post('feedback/store',                 ['as' => 'feedback.store',           'uses' => 'FeedbackController@store']);
    Route::get('feedback/{id}/edit',              ['as' => 'feedback.edit',            'uses' => 'FeedbackController@edit']);
    Route::post('feedback/{id}/update',          ['as' => 'feedback.update',          'uses' => 'FeedbackController@update']);
    Route::get('feedback/{id}/delete',           ['as' => 'feedback.delete',          'uses' => 'FeedbackController@delete']);

    Route::get('banner',                        ['as' => 'banner.index',           'uses' => 'BannerController@index']);
    Route::get('banner/add',                    ['as' => 'banner.add',             'uses' => 'BannerController@add']);
    Route::post('banner/store',                 ['as' => 'banner.store',           'uses' => 'BannerController@store']);

app/Models/AboutUs.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class AboutUs extends Model
{
    protected $table = 'about_us';

    // protected $timestamp = false;

    protected $guarded = [];

    protected $fillable = ['title', 'slug', 'image', 'description', 'status'];




}

app/Http/Controllers/Admin/AboutUsController.php
<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 11/15/16
 * Time: 7:29 AM
 */
namespace App\Http\Controllers\Admin;
use App\Http\Requests\AboutUs\AddValidation;
use App\Http\Requests\AboutUs\EditValidation;
use App\Models\AboutUs;
use App\Models\Menu;
use App\Models\Page;
use Illuminate\Http\Request;


class AboutUsController extends AdminBaseController
{
    protected $base_route = 'admin.about-us';
    protected $view_path = 'admin.about-us';
    protected $view_title = 'AboutUs Manger';
    protected $folder_name = 'about-us';
    public $trans_path = 'santosh';
    protected $listing;
    protected $folder_path;

    public function __construct()
    {
        $this->folder_path = public_path().DIRECTORY_SEPARATOR.'images'.DIRECTORY_SEPARATOR.$this->folder_name.DIRECTORY_SEPARATOR;
    }


    public function index(Request $request)
    {
        $menu_id = Menu::select('id')->where('slug','=',$this->folder_name)->first();
        $data = [];
        $data['rows'] = Menu::select()->where('parent_menu','=',$menu_id->id)->get();

        return view(parent::loadDefaultVars($this->view_path.'.list'), compact('data'));
    }

    public function add(Request $request)
    {
        $data = [];
        return view(parent::loadDefaultVars($this->view_path.'.add'), compact('data'));
    }

    public function store(AddValidation $request)
    {

        $slug = str_slug($request->get('title'));

        Page::create([
            'title' => $request->get('title'),
            'slug' => $slug,
            'description' => $request->get('description'),
            'parent_menu' => $request->get('parent_menu'),
            'page_link' => $request->get('page_link'),
            'status' => $request->get('status'),
        ]);

        $parent_menu = Menu::select('id')->where('slug','=',$this->folder_name)->first();
        $page_id = Page::select('id')->where('slug','=',$slug)->first();

        Menu::create([
            'title' => $request->get('title'),
            'slug' => $slug,
            'link' => null,
            'page_id' => $page_id->id,
            'parent_menu' => $parent_menu->id,
            'target' => 0,
            'status' => $request->get('status'),
        ]);

        /*if ($request->hasFile('image')){
            $image = $request->file('image');
            $file_name = rand(0000 , 9999) . '_' . $image->getClientOriginalName();
            $image->move($this->folder_path,$file_name);
        }

       $list = AboutUs::create([
           'title'               =>     $request->get('title'),
           'slug' => str_slug($request->get('title')),
           'image'               =>     $file_name,
           'description'               =>     $request->get('description'),
           'status'          =>     $request->get('status'),
        ]);*/

        $request->session()->flash('message', 'AboutUs added successfully.');
        return redirect()->route($this->base_route.'.index');
    }

    public function edit(Request $request, $menu_id, $page_id)
    {

        // get user data for $id
        //dd($id);
        $data = [];

        if (!$data['menu'] = Menu::find($menu_id))
            return redirect()->route('admin.error', ['code' => '500']);

        if (!$data['santosh'] = Page::find($page_id))
            return redirect()->route('admin.error', ['code' => '500']);

        $data['menu_id'] = $data['menu']->id;
        $data['page_id'] = $data['santosh']->id;

        $data['row'] = Menu::select()->first();

        return view(parent::loadDefaultVars($this->view_path.'.edit'), compact('data'));
    }

    public function update(EditValidation $request, $menu_id, $page_id)
    {
        if (!$menu = Menu::find($menu_id))
            return redirect()->route('admin.error', ['code' => '500']);

        if (!$page = Page::find($page_id))
            return redirect()->route('admin.error', ['code' => '500']);

        $page->update([
            'title' => $request->get('title'),
            'description' => $request->get('description'),
            'parent_menu' => $request->get('parent_menu'),
            'page_link' => $request->get('page_link'),
            'status' => $request->get('status'),
        ]);

        $menu->update([
            'title' => $request->get('title'),
            'status' => $request->get('status'),
        ]);


        $request->session()->flash('message', 'AboutUs updated successfully.');
        return redirect()->route($this->base_route.'.index');
    }

    public function delete(Request $request, $menu_id, $page_id)
    {
       //dd('enter');
        if (!$menu = Menu::find($menu_id))
            return redirect()->route('admin.error', ['code' => '500']);

        if (!$page = Page::find($page_id))
            return redirect()->route('admin.error', ['code' => '500']);

        $menu->delete();
        $page->delete();
        $request->session()->flash('message', 'AboutUs deleted successfully.');
        return redirect()->route($this->base_route.'.index');

    }

    public function imgDelete(Request $request)
    {

        $id = $request->get('id');

        $response = [];
        $response['error'] = true;

        if (!$listing = AboutUs::find($id)){
            $response['message'] = 'data not found';
        }else{

            if($listing->image ==! '')
            $listing->update([
                'image'               =>     null,
            ]);

            $response['error'] = false;

        }

        return response()->json(json_encode($response));

    }

    public function search(Request $request)
    {
        dd($request->all());
    }

}

resources/views/admin/about-us/partials/breadcrumb.blade.php
<ul class="breadcrumb">
    <li>
        <i class="icon-home home-icon"></i>
        <a href="{{ route('admin.dashboard') }}">{{ trans('general.home') }}</a>
    </li>

    <li>
        <a href="{{ route($base_route.'.index') }}">{{ $view_title }} </a>
    </li>

    @if (isset($data))
        <li class="active">{{ trans($trans_path.'content.common.edit') }} </li>
    @else
        <li class="active">{{ trans($trans_path.'content.common.add') }} </li>
    @endif

</ul><!-- .breadcrumb -->

resources/views/admin/about-us/partials/form.blade.php
<script src="{{ asset('vendor/unisharp/laravel-ckeditor/ckeditor.js') }}"></script>

<div class="space-4"></div>


<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right" for="title"> Title </label>

    <div class="col-sm-9">
        <input type="text" name="title" id="title" value="{{ ViewHelper::getData('title', isset($data['santosh'])?$data['santosh']:[]) }}" placeholder="Title" class="col-xs-10 col-sm-5">
    </div>
</div>
<div class="space-4"></div>

<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right" for="description"> Description </label>

    <div class="col-sm-9">
        <textarea name="description" id="description" placeholder="Description" class="col-xs-10 col-sm-5">{{ ViewHelper::getData('description', isset($data['santosh'])?$data['santosh']:[]) }}</textarea>
        <script>
            CKEDITOR.replace( 'description', {
                filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
                filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token={{csrf_token()}}',
                filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
                filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token={{csrf_token()}}'
            });
        </script>
    </div>
</div>
<div class="space-4"></div>

<div class="form-group" id="parent_menu_hide_gar">
    <label class="col-sm-3 control-label no-padding-right" for="parent_menu"> Page Link </label>

    <div class="col-sm-9">
        <select name="page_link" id="parent_menu" class="col-xs-10 col-sm-5">
            <option value="gallery" {!! (isset($data['row']->page_link) && $data['row']->page_link=='gallery')?'selected':'' !!}>Gallery</option>
            <option value="about" {!! (isset($data['row']->page_link) && $data['row']->page_link=='about')?'selected':'' !!}>About Us</option>
            <option value="contact" {!! (isset($data['row']->page_link) && $data['row']->page_link=='contact')?'selected':'' !!}>Contact Us</option>
            <option value="newss" {!! (isset($data['row']->page_link) && $data['row']->page_link=='newss')?'selected':'' !!}>News</option>
            <option value="simplepage" {!! (isset($data['row']->page_link) && $data['row']->page_link=='simplepage')?'selected':'' !!}>Simple Page</option>
        </select>

    </div>
</div>
<div class="space-4"></div>

<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right" for="status"> Status </label>

    <div class="col-sm-9">
        <div class="radio">
            <label>
                <input name="status" value="1" checked type="radio" class="ace">
                <span class="lbl"> Active</span>
            </label>
        </div>
        <div class="radio">
            <label>
                <input name="status" value="0" type="radio" class="ace">
                <span class="lbl"> In-active</span>
            </label>
        </div>
    </div>
</div>
<div class="space-4"></div>

@if(isset($data['row']))

<script>
    
    $(document).ready(function () {
        $('#delete_image_aboutus').click(function () {
            $.ajax({
                type : 'POST',
                url : '{{ route('admin.image.about-us.delete') }}',
                data : {
                    _token : '{{ csrf_token() }}',
                    id : {{ $data['row']->id }}
                },
                success : function (response) {
                    var data = $.parseJSON(response);

                    if (data.error){

                    }else{
                        alert('delete successful');
                        $('#aboutus_image_div').hide();
                        $('#old_image_val').val(null);
                    }

                },
                error : {

                }
            });
        });
    });

</script>

    @endif