routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});
Route::get('',                    ['as' => 'index',             'uses' => 'WebPage\WebPageController@index']);
Route::get('about',                    ['as' => 'about',             'uses' => 'WebPage\WebPageController@about']);
Route::get('gallerys',                    ['as' => 'gallery',             'uses' => 'WebPage\WebPageController@gallery']);
Route::get('gallerys/{slug}',                    ['as' => 'photo',             'uses' => 'WebPage\WebPageController@gallery']);
Route::get('contact-us',                    ['as' => 'contact-us',             'uses' => 'WebPage\WebPageController@contact']);
Route::get('newses/{slug}',                    ['as' => 'newss',             'uses' => 'WebPage\WebPageController@news']);
Route::get('newses',                    ['as' => 'newses',             'uses' => 'WebPage\WebPageController@news']);
Route::get('alumni',                    ['as' => 'alumni',             'uses' => 'WebPage\WebPageController@alumni']);
Route::get('careers',                    ['as' => 'careers',             'uses' => 'WebPage\WebPageController@careers']);
Route::get('informations',                    ['as' => 'informations',             'uses' => 'WebPage\WebPageController@information']);
Route::get('club-and-ecas',                    ['as' => 'club-and-eca',             'uses' => 'WebPage\WebPageController@clubAndEca']);
Route::get('downloads',                    ['as' => 'download',             'uses' => 'WebPage\WebPageController@download']);
Route::get('simplepage/{slug}',                    ['as' => 'simplepage',             'uses' => 'WebPage\WebPageController@page']);
Route::post('feedback/stores',                 ['as' => 'feedback.store',           'uses' => 'Admin\FeedbackController@store']);

Auth::routes();

//Route::get('/', function () {
//    return redirect('login');
//});

Route::get('/home', function () {
    return redirect()->route('admin.dashboard');
});

Route::group(['middleware' => ['auth', 'status'], 'prefix' => '', 'as' => 'admin.', 'namespace' => 'Admin\\'], function () {

    Route::get('dashboard', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
    Route::get('error/{code}',                        ['as' => 'error',                 'uses' => 'DashboardController@error']);

    Route::get('profile', ['as' => 'profile', 'uses' => 'ProfileController@edit']);
    Route::post('profile/{id}/update', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::post('profile/{id}/delete', ['as' => 'profile.delete', 'uses' => 'ProfileController@delete']);

    Route::get('menu',['as' => 'menu', 'uses' => 'MenuController@index']);

    Route::get('principle',                    ['as' => 'principle.add',             'uses' => 'PrincipleController@add']);
    Route::post('principle/{id}/update',          ['as' => 'principle.update',          'uses' => 'PrincipleController@update']);
    Route::post('principle/{id}/delete',          ['as' => 'principle.image.delete',          'uses' => 'PrincipleController@imageDelete']);

    Route::get('about-us',                        ['as' => 'about-us.index',           'uses' => 'AboutUsController@index']);
    Route::post('about-us-search',                        ['as' => 'about-us.search',           'uses' => 'AboutUsController@search']);
    Route::get('about-us/add',                    ['as' => 'about-us.add',             'uses' => 'AboutUsController@add']);
    Route::post('about-us/store',                 ['as' => 'about-us.store',           'uses' => 'AboutUsController@store']);
    Route::get('about-us/{menu_id}/{page_id}/edit',              ['as' => 'about-us.edit',            'uses' => 'AboutUsController@edit']);
    Route::post('about-us/{menu_id}/{page_id}/update',          ['as' => 'about-us.update',          'uses' => 'AboutUsController@update']);
    Route::get('about-us/{menu_id}/{page_id}/delete',           ['as' => 'about-us.delete',          'uses' => 'AboutUsController@delete']);
    Route::post('about-us/delete',           ['as' => 'image.about-us.delete',          'uses' => 'AboutUsController@imgDelete']);

    Route::get('information',                        ['as' => 'information.index',           'uses' => 'InformationController@index']);
    Route::post('information-search',                        ['as' => 'information.search',           'uses' => 'InformationController@search']);
    Route::get('information/add',                    ['as' => 'information.add',             'uses' => 'InformationController@add']);
    Route::post('information/store',                 ['as' => 'information.store',           'uses' => 'InformationController@store']);
    Route::get('information/{menu_id}/{page_id}/edit',              ['as' => 'information.edit',            'uses' => 'InformationController@edit']);
    Route::post('information/{menu_id}/{page_id}/update',          ['as' => 'information.update',          'uses' => 'InformationController@update']);
    Route::get('information/{menu_id}/{page_id}/delete',           ['as' => 'information.delete',          'uses' => 'InformationController@delete']);
    Route::post('information/delete',           ['as' => 'image.information.delete',          'uses' => 'InformationController@imgDelete']);

    Route::get('club-and-eca',                        ['as' => 'club-and-eca.index',           'uses' => 'ClubAndEcaController@index']);
    Route::post('club-and-eca-search',                        ['as' => 'club-and-eca.search',           'uses' => 'ClubAndEcaController@search']);
    Route::get('club-and-eca/add',                    ['as' => 'club-and-eca.add',             'uses' => 'ClubAndEcaController@add']);
    Route::post('club-and-eca/store',                 ['as' => 'club-and-eca.store',           'uses' => 'ClubAndEcaController@store']);
    Route::get('club-and-eca/{menu_id}/{page_id}/edit',              ['as' => 'club-and-eca.edit',            'uses' => 'ClubAndEcaController@edit']);
    Route::post('club-and-eca/{menu_id}/{page_id}/update',          ['as' => 'club-and-eca.update',          'uses' => 'ClubAndEcaController@update']);
    Route::get('club-and-eca/{menu_id}/{page_id}/delete',           ['as' => 'club-and-eca.delete',          'uses' => 'ClubAndEcaController@delete']);
    Route::post('club-and-eca/delete',           ['as' => 'image.club-and-eca.delete',          'uses' => 'ClubAndEcaController@imgDelete']);

    Route::get('gallery',                        ['as' => 'gallery.index',           'uses' => 'GalleryController@index']);
    Route::get('gallery/add',                    ['as' => 'gallery.add',             'uses' => 'GalleryController@add']);
    Route::post('gallery/store',                 ['as' => 'gallery.store',           'uses' => 'GalleryController@store']);
    Route::get('gallery/{id}/edit',              ['as' => 'gallery.edit',            'uses' => 'GalleryController@edit']);
    Route::post('gallery/{id}/update',          ['as' => 'gallery.update',          'uses' => 'GalleryController@update']);
    Route::get('gallery/{id}/delete',           ['as' => 'gallery.delete',          'uses' => 'GalleryController@delete']);

    Route::get('photo',                        ['as' => 'photo.index',           'uses' => 'PhotoController@index']);
    Route::get('photo/add',                    ['as' => 'photo.add',             'uses' => 'PhotoController@add']);
    Route::post('photo/store',                 ['as' => 'photo.store',           'uses' => 'PhotoController@store']);
    Route::get('photo/{id}/edit',              ['as' => 'photo.edit',            'uses' => 'PhotoController@edit']);
    Route::post('photo/{id}/update',          ['as' => 'photo.update',          'uses' => 'PhotoController@update']);
    Route::get('photo/{id}/delete',           ['as' => 'photo.delete',          'uses' => 'PhotoController@delete']);

    Route::get('feature',                        ['as' => 'feature.index',           'uses' => 'FeatureController@index']);
    Route::get('feature/add',                    ['as' => 'feature.add',             'uses' => 'FeatureController@add']);
    Route::post('feature/store',                 ['as' => 'feature.store',           'uses' => 'FeatureController@store']);
    Route::get('feature/{id}/edit',              ['as' => 'feature.edit',            'uses' => 'FeatureController@edit']);
    Route::post('feature/{id}/update',          ['as' => 'feature.update',          'uses' => 'FeatureController@update']);
    Route::get('feature/{id}/delete',           ['as' => 'feature.delete',          'uses' => 'FeatureController@delete']);

    Route::get('feedback',                        ['as' => 'feedback.index',           'uses' => 'FeedbackController@index']);
    Route::get('feedback/add',                    ['as' => 'feedback.add',             'uses' => 'FeedbackController@add']);
    Route::post('feedback/store',                 ['as' => 'feedback.store',           'uses' => 'FeedbackController@store']);
    Route::get('feedback/{id}/edit',              ['as' => 'feedback.edit',            'uses' => 'FeedbackController@edit']);
    Route::post('feedback/{id}/update',          ['as' => 'feedback.update',          'uses' => 'FeedbackController@update']);
    Route::get('feedback/{id}/delete',           ['as' => 'feedback.delete',          'uses' => 'FeedbackController@delete']);

    Route::get('banner',                        ['as' => 'banner.index',           'uses' => 'BannerController@index']);

app/Models/Principle.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Principle extends Model
{
    protected $table = 'principle';

    // protected $timestamp = false;

    protected $guarded = [];

    protected $fillable = ['title', 'image', 'slug', 'message', 'status'];




}

app/Http/Controllers/Admin/PrincipleController.php
<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 11/15/16
 * Time: 7:29 AM
 */
namespace App\Http\Controllers\Admin;
use App\Http\Requests\Principle\AddValidation;
use App\Http\Requests\Principle\EditValidation;
use App\Models\Principle;
use Illuminate\Http\Request;


class PrincipleController extends AdminBaseController
{
    protected $base_route = 'admin.principle';
    protected $view_path = 'admin.principle';
    protected $view_title = 'Principle Manger';
    protected $folder_name = 'principle';
    protected $trans_path = 'banner';
    protected $folder_path;

    public function __construct()
    {
        $this->folder_path = public_path().DIRECTORY_SEPARATOR.'images'.DIRECTORY_SEPARATOR.$this->folder_name.DIRECTORY_SEPARATOR;
    }

    public function add(Request $request)
    {

        $data = [];
        $data['row'] = Principle::select()->first();

        return view(parent::loadDefaultVars($this->view_path.'.add'), compact('data'));
    }

    public function update(EditValidation $request, $id)
    {

        if (!$listing = Principle::find($id)){

            if ($request->hasFile('image')){
                $image = $request->file('image');
                $file_name = rand(0000 , 9999) . '_' . $image->getClientOriginalName();
                $image->move($this->folder_path,$file_name);
            }else{
                $file_name = $request->get('oldimg');
            }

            $list = Principle::create([
                'title'               =>     $request->get('title'),
                'slug'               =>     str_slug($request->get('title')),
                'image'                =>    $file_name,
                'message'          =>     $request->get('message'),
                'status' => $request->get('status'),
            ]);
        }else{



            if ($request->hasFile('image')){
                $image = $request->file('image');
                $file_name = rand(0000 , 9999) . '_' . $image->getClientOriginalName();
                $image->move($this->folder_path,$file_name);

//                if(isset($listing->image) && !empty($listing->image))
//                    unlink($this->folder_path.$listing->image);

            }else{
                $file_name = $request->get('oldimg');
            }

            $listing->update([
                'title'               =>     $request->get('title'),
                'slug'               =>     str_slug($request->get('title')),
                'image'                =>    $file_name,
                'message'          =>     $request->get('message'),
                'status' => $request->get('status'),
            ]);
        }

        $request->session()->flash('message', 'Principle updated successfully.');
        return redirect()->route($this->base_route.'.add');
    }

    public function imageDelete(Request $request, $id)
    {

        $type = $request->get('type');
        $value = $request->get('value');

        $response = [];

        $response['error'] = true;

        if (!$listing = Principle::find($id))
            $response['message'] = 'data not found';


        // remove image before deleting db row

        /*if($listing->image ==! '')
            unlink($this->folder_path.$listing->image);*/

        switch ($type){
            case image:
                $listing->update([
                    'image'                =>    null,
                ]);
                break;
            case title:
                $listing->update([
                    'title'                =>    $value,
                ]);
                break;


        }

        if(isset($listing->image))
            unlink($this->folder_path.$listing->image);

        $response['error'] = false;

        return response()->json(json_encode($response));

    }



}

resources/views/admin/principle/partials/breadcrumb.blade.php
<ul class="breadcrumb">
    <li>
        <i class="icon-home home-icon"></i>
        <a href="{{ route('admin.dashboard') }}">{{ trans('general.home') }}</a>
    </li>

    <li>
        <a href="{{ route($base_route.'.add') }}">{{ $view_title }} </a>
    </li>

    @if (isset($data))
        <li class="active">{{ trans($trans_path.'content.common.edit') }} </li>
    @else
        <li class="active">{{ trans($trans_path.'content.common.add') }} </li>
    @endif

</ul><!-- .breadcrumb -->

resources/views/admin/principle/partials/form.blade.php
<script src="{{ asset('vendor/unisharp/laravel-ckeditor/ckeditor.js') }}"></script>
<div class="space-4"></div>


<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right" for="title_principle_name"> Title </label>

    <div class="col-sm-9">
        <input type="text" name="title" id="title_principle_name" value="{{ ViewHelper::getData('title', isset($data['row'])?$data['row']:[]) }}" placeholder="Title" class="col-xs-10 col-sm-5">
    </div>
</div>
<div class="space-4"></div>

@if(isset($data['row']['image']) && !empty($data['row']['image']))
<div id="image_group">
    <div class="form-group">
        <label class="col-sm-3 control-label no-padding-right" for="image"> Old Image </label>

        <lable class="col-sm-9">

            <img src="{{ asset('images/principle/'.$data['row']['image']) }}" width="200px" for="image" alt="">
            <a href="#" id="remove_principle_image">
                <i class="icon-remove"></i>
            </a>
        </lable>
    </div>
    <div class="space-4"></div>

    <input type="hidden" id="old_image_val" value="{{ $data['row']['image'] }}" name="oldimg">
</div>
    @endif
<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right" for="image_upload"> Image </label>

    <div class="col-sm-9">

        <input type="file" name="image" id="image_upload" value="{{ ViewHelper::getData('image', isset($data['row'])?$data['row']:[]) }}" placeholder="Image" class="col-xs-10 col-sm-5">
    </div>
</div>
<div class="space-4"></div>

<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right" for="message"> Principle's Message </label>

    <div class="col-sm-9">
        <textarea name="message" id="message" placeholder="Principle's Message" class="col-xs-10 col-sm-5">{{ ViewHelper::getData('message', isset($data['row'])?$data['row']:[]) }}</textarea>
        <script>
            CKEDITOR.replace( 'description', {
                filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
                filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token={{csrf_token()}}',
                filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
                filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token={{csrf_token()}}'
            });
        </script>
    </div>
</div>
<div class="space-4"></div>

<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right" for="status"> Status </label>

    <div class="col-sm-9">
        <div class="radio">
            <label>
                <input name="status" value="1" checked type="radio" class="ace">
                <span class="lbl"> Active</span>
            </label>
        </div>
        <div class="radio">
            <label>
                <input name="status" value="0" type="radio" class="ace">
                <span class="lbl"> In-active</span>
            </label>
        </div>
    </div>
</div>
<div class="space-4"></div>



<script>
    $(document).ready(function () {
        $('#remove_principle_image').click(function () {
            ajax('image','nth');
        });
        $('#title_principle_name').change(function () {
            ajax('title',$('#title_principle_name').val());
        });
    });


    function ajax($input,$value) {
        $.ajax({
            method : 'post',
            url : '{{ route('admin.principle.image.delete',$data['row']['id']) }}',
            data : {
                _token : '{{ csrf_token() }}',
                type : $input,
                value : $value
            },

            success : function (response) {

                var data = $.parseJSON(response);
                if (data.error){

                }else{
                    $('#image_group').hide(500);
                    $('#old_image_val').val(null);
                }

            },
        });
    }

</script>